<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../build/Avalonia.props" />
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<OutputType>Library</OutputType>
		<Nullable>disable</Nullable>
		<RosDir>../../reactos</RosDir>
		<!--
		<RootNamespace>ReactiveDream</RootNamespace>
		-->
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets/**" />
		<AvaloniaResource Include="placeholder/**" />

		<!--
		https://blog.nerdbank.net/2023/04/11/embedded-resources-in-c-projects-that-retain-slashes/
		-->
		<EmbeddedResource Include="$(RosDir)/modules/**">
			<LogicalName>$([System.String]::Copy('%(RecursiveDir)').Replace('\','/'))%(Filename)</LogicalName>
		</EmbeddedResource>
		<!--
		<EmbeddedResource Include="$(RosDir)/media/themes/Reactive/reactive.msstyles/bitmaps/**">
			<LogicalName>%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
		</EmbeddedResource>
		-->
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Skia" Version="$(AvVer)" />
		<PackageReference Include="Avalonia.Diagnostics" Version="$(AvVer)" />
		<PackageReference Include="Avalonia.ReactiveUI" Version="$(AvVer)" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvVer)" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvVer)" />

        <PackageReference Include="Svg.Skia" Version="1.0.0.16" />
	</ItemGroup>
</Project>